image: golang

variables:
  BUILD_PATH: ./

stages:
  - build
  - publish

build:
  stage: build
  cache:
    key: build-package
    policy: push
    paths:
      - ${BUILD_PATH}
  only:
    - master
  script:
    - go mod tidy
    - go mod vendor
    - go build

tag:
  stage: build
  only:
    - master
  dependencies:
    - build
  script:
    - git config user.name "Rodrigo Odhin"
    - git config user.email rodrigoodhin@gmail.com
    - git remote add demo-tag-origin https://oauth2:${GITLAB_ACCESS_TOKEN}@gitlab.com/${CI_PROJECT_PATH}
    - git tag -a "Release_$(date +%Y-%m-%d)" -m "Auto-Release"
    - git push demo-tag-origin "Release_$(date +%Y-%m-%d)"

publish:
  image: inetprocess/gitlab-release
  stage: publish
  cache:
    key: build-package
    policy: pull
  only:
    - master
  dependencies:
    - build
    - tag
  script:
    - gitlab-release --message 'Automatic release' go-editorjs-parser