variables:
  PROJECT_NAME: go-editorjs-parser

stages:
  - tag
  - release

tag:
  stage: tag
  only:
    - master
  script:
    - git config user.name "Rodrigo Odhin"
    - git config user.email rodrigoodhin@gmail.com
    - git remote add demo-tag-origin https://oauth2:${GITLAB_ACCESS_TOKEN}@gitlab.com/${CI_PROJECT_PATH}
    - git tag -a "${PROJECT_NAME}_$(date +%Y-%m-%d)" -m "Auto-Release"
    - git push demo-tag-origin "${PROJECT_NAME}_$(date +%Y-%m-%d)"

release-branch:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli
  when: manual
  script:
    - >
      release-cli create --name "${PROJECT_NAME}_$(date +%Y-%m-%d)" --description "${PROJECT_NAME} - $(date +%Y-%m-%d)"
      --tag-name "${PROJECT_NAME}_$(date +%Y-%m-%d)" --ref $CI_COMMIT_SHA
      --released-at "$(date +%Y-%m-%d %H:%M:%S)"
