image: "ubuntu"

variables:
  BUILD_PATH: ./
  PROJECT_NAME: go-editorjs-parser

stages:
  - package

package project:
  stage: package
  artifacts:
    name: "$PROJECT_NAME-$CI_COMMIT_REF_NAME"
    when: always
    paths:
      - ${BUILD_PATH}
  script:
    - pwd
  only:
    - master