image: golang

variables:
  BUILD_FILE: go-editorjs-parser

stages:
  - build
  - tag
  - publish

build:
  stage: build
  artifacts:
    expire_in: '1 hour'
    paths:
      - ${BUILD_FILE}
  only:
    - master
  script:
    - go mod tidy
    - go mod vendor
    - go build

tag:
  stage: tag
  dependencies:
    - build
  only:
    - master
  script:
    - git config user.name "Rodrigo Odhin"
    - git config user.email rodrigoodhin@gmail.com
    - git remote add demo-tag-origin https://oauth2:${GITLAB_ACCESS_TOKEN}@gitlab.com/${CI_PROJECT_PATH}
    - git tag -a "Release_$(date +%Y-%m-%d)" -m "Auto-Release"
    - git push demo-tag-origin "Release_$(date +%Y-%m-%d)"

publish:
  image: inetprocess/gitlab-release
  stage: publish
  only:
    - master
  dependencies:
    - build
    - tag
  script:
    - gitlab-release --message 'Automatic release' ${BUILD_FILE}