image: node

variables:
  BUILD_PATH: ./build
  PROJECT_NAME: go-editorjs-parser

stages:
  - build
  - publish

build:
  stage: build
  only:
    - master
  script:
    - mkdir build
    - cp -r ./domain ./build
    - cp -r ./helpers ./build
    - cp -r ./parser ./build
    - cp -r ./pkg ./build
    - cp go.mod ./build
    - cp goEditorjsParser.go ./build
  artifacts:
    paths:
      - ${BUILD_PATH}

tag:
  stage: build
  only:
    - master
  script:
    - git config user.name "Rodrigo Odhin"
    - git config user.email rodrigoodhin@gmail.com
    - git remote add demo-tag-origin https://oauth2:${GITLAB_ACCESS_TOKEN}@gitlab.com/${CI_PROJECT_PATH}
    - git tag -a "Release_$(date +%Y-%m-%d)" -m "Auto-Release"
    - git push demo-tag-origin "Release_$(date +%Y-%m-%d)"

publish:
  stage: publish
  only:
    - master
  dependencies:
    - build
  script:
    - gitlab-release --message 'Automatic release' ${BUILD_PATH}