variables:
  TAG_NAME: "v$(date +%y.%m.%d)"

stages:
  - tag
  - release

create-tag:
  stage: tag
  only:
    - master
  script:
    - git config user.name "Rodrigo Odhin"
    - git config user.email rodrigoodhin@gmail.com
    - git remote add demo-tag-origin https://oauth2:${GITLAB_ACCESS_TOKEN}@gitlab.com/${CI_PROJECT_PATH}
    - git tag -a "${TAG_NAME}" -m "Auto-Release"
    - git push demo-tag-origin "${TAG_NAME}"

create-release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli
  only:
    - master
  dependencies:
    - create-tag
  script:
    - >
      release-cli create --name "${TAG_NAME}" --description "Version ${TAG_NAME} created at $(date +%Y-%m-%d)"
      --tag-name "${TAG_NAME}" --ref $CI_COMMIT_SHA
      --released-at "$(date +%Y-%m-%d %H:%M:%S)"
